create table vessel (
    name varchar(255) not null, 
    imo int not null,
    length smallint not null,
    primary key (imo)
);

create table port(
    port_id smallint not null,
    primary key (port_id)
);

create table port_vessel(
    id bigint generated by default as identity,
    port_id smallint references port(port_id), 
    imo int references vessel(imo), 
    time_started timestamp(3) not null, 
    time_finished timestamp(3) not null,
    primary key (id)
);

create index portvessel_index_portid_imo on port_vessel(port_id, imo);